=== YellLabs/bragger/samples/wsdl2java/wsdl2.0/bookstore/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
   targetNamespace="http://www.bookstore.org/book/xsd"
   xmlns:tns="http://www.bookstore.org/book/xsd"
   elementFormDefault="qualified">
   
  <element name="book" type="tns:bookType">
    <annotation>
      <documentation>
         The response element for the book service.
      </documentation>
    </annotation>
  </element>
  
  <complexType name="bookType">
    <sequence>
      <element name="title" type="string"/>
      <element name="author" type="tns:authorType" minOccurs="1" maxOccurs="unbounded"/>
      <element name="overview" type="string"/>
      <element name="pages" type="positiveInteger"/>
      <element name="publisher" type="string"/>
      <element name="language" type="string"/>
      <element name="isbn-10" type="tns:isbn10Type"/>
      <element name="isbn-13" type="tns:isbn13Type"/>
      <element name="price" type="decimal"/>
    </sequence>
  </complexType>

  <complexType name="authorType">
    <sequence>
      <element name="firstName" type="string"/>
      <element name="lastName" type="string"/>
    </sequence>
  </complexType>

  <simpleType name="isbn10Type">
    <restriction base="integer">
      <pattern value="\d{10}"/>
    </restriction>
  </simpleType>

  <simpleType name="isbn13Type">
    <restriction base="string">
      <pattern value="\d{3}\-\d{10}"/>
    </restriction>
  </simpleType>
</schema>

=== YellLabs/bragger/samples/wsdl2java/wsdl2.0/bookstore/0321396855.xml
<?xml version="1.0" encoding="UTF-8"?>
<book:book xmlns:book="http://www.bookstore.org/book/xsd" 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xsi:schemaLocation="http://www.bookstore.org/book/xsd book.xsd">
  <book:title>Eclipse Web Tools Platform: Developing Java Web Applications</book:title>
  <book:author>
    <book:firstName>Naci</book:firstName>
    <book:lastName>Dai</book:lastName>
  </book:author>
  <book:author>
    <book:firstName>Lawrence</book:firstName>
    <book:lastName>Mandel</book:lastName>
  </book:author>
  <book:author>
    <book:firstName>Arthur</book:firstName>
    <book:lastName>Ryman</book:lastName>
  </book:author>
  <book:overview>
    Discover WTP, the New End-to-End Toolset for Java-Based Web Development
    The Eclipse Web Tools Platform (WTP) seamlessly integrates all the tools today’s Java
    Web developer needs. WTP is both an unprecedented Open Source resource for working
    developers and a powerful foundation for state-of-the-art commercial products.
    Eclipse Web Tools Platform offers in-depth descriptions of every tool included in
    WTP, introducing powerful capabilities never before available in Eclipse. The authors
    cover the entire Web development process–from defining Web application architectures
    and development processes through testing and beyond. And if you’re seeking to extend
    WTP, this book provides an introduction to the platform’s rich APIs. The book also
  </book:overview>
  <book:pages>752</book:pages>
  <book:publisher>Addison-Wesley Professional</book:publisher>
  <book:language>English</book:language>
  <book:isbn-10>0321396855</book:isbn-10>
  <book:isbn-13>978-0321396853</book:isbn-13>
  <book:price>54.99</book:price>
</book:book>
